### ISSUE TITLE
payloadExtender is not supported in default shipping-save-processor

### ISSUE THREAD

**Issue by martin-cod** [classyllama/ClassyLlama_AvaTax#181]
The following file vendor/classyllama/module-avatax/view/frontend/web/js/model/shipping-save-processor/default.js overwrites the core file 
vendor/magento/module-checkout/view/frontend/web/js/model/shipping-save-processor/default.js
Since Magento 2.2 default shipping-save-processor supports payloadExtender to allow third party extensions to modify the payload for the shipping address selection process

### Preconditions
1. Magento 2.2.5
2. avalara/avatax 15.5.2
3. PHP 7.1.20

### Steps to reproduce
1. Add product to cart and got to checkout
2. locate the static js file file in the browser dev tools static/../../Magento_Checkout/js/model/shipping-save-processor/payload-extender.js

### Expected result
1. The file should be loaded
2. Overwritten shipping-save-processor/default.js file should support payloadExtender

### Actual result
1. File is not loaded

**Comment by rsisco** [comment]
@martin-cod - Thank you for reporting this issue. We are working on a solution that will retain backward-compatibility with Magento 2.1.x, since it is still officially supported by the extension.

**Comment by rsisco** [comment]
Update: These changes have been merged and will be included in the next release of the extension.

@sjb9774 - These changes need to be merged into the 2.x branch as well.

**Comment by rsisco** [comment]
This issue has been addressed in release [1.5.0](https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/1.5.0).

**Comment by martin-cod** [comment]
@rsisco I have just reviewed the code in release 1.5.0. and found that the file vendor/classyllama/module-avatax/view/frontend/web/js/model/shipping-save-processor/default.js became a mixin but payloadExtender is still not supported. Could you please check it once again?
![payloadextender](https://user-images.githubusercontent.com/33550246/50373602-9d40b980-05f2-11e9-953b-dda50c670ca0.png)

**Comment by rsisco** [comment]
@martin-cod - Can you provide a use case you are trying to support so that we may properly refactor and test the code if applicable? The original issue stated that the problem was that we were overriding the core default.js file and losing the payload extender, which is now not the case.

**Comment by martin-cod** [comment]
@rsisco Please follow the Magento official change to be able to identify what is missed in your mixin's saveShippingInformation method https://github.com/magento/magento2/commit/9fc22ff2fe2e0c62d75d00d8ce1d55207ea6462b#diff-6f15bee8297c1e4e27c4d32164904b80

I used payloadExtender object in my custom code to extend shippingInformation save processor. Having AvaTax module installed I lost that possibility. Hope it helps.

**Comment by joshuaadickerson** [comment]
The only thing to do to get that supported in 2.2 is to add that payloadExtender line as @martin-cod said. Without it, it breaks a lot of functionality for us.

**Comment by prestonchoate** [comment]
@martin-cod I just merged some code into develop that @sjb9774 worked on to address this. Could you pull that down and see if it resolves the issue. If so I will prep it for a new official release. Thanks!

**Comment by kriby** [comment]
@rsisco here is the use case - I want to use payload-extender to pass extension attributes data to the server.

**Comment by kriby** [comment]
@prestonchoate I've checked out develop branch and it looks like it is working. I am able to use payload-extender on checkout.
Verified on 2.2.5 Commerce edition

**Comment by prestonchoate** [comment]
@kriby Perfect. I'll add this to the list of changes for the next version release.

**Comment by kriby** [comment]
@prestonchoate what is the target date for the next release?

**Comment by prestonchoate** [comment]
@kriby Not entirely sure yet. Probably next week some time.

**Comment by prestonchoate** [comment]
Released in version 1.5.1. Please update the extension.
